import { SourcedJobData } from './types'

function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}

function hoursAgo(n: number): Date {
  const d = new Date()
  d.setHours(d.getHours() - n)
  return d
}

export const MOCK_JOBS: SourcedJobData[] = [
  {
    title: 'Senior Machine Learning Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/openai-ml-1',
    source: 'Company Site',
    description: 'Join the team building the next generation of AI models. You will work on training infrastructure, model optimization, and deployment pipelines.',
    posted_at: hoursAgo(3),
  },
  {
    title: 'LLM Research Engineer',
    company: 'Anthropic',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/anthropic-llm-1',
    source: 'Greenhouse',
    description: 'Research and develop large language models with a focus on safety and alignment. Strong background in transformers and distributed training required.',
    posted_at: hoursAgo(8),
  },
  {
    title: 'AI Product Engineer',
    company: 'Cohere',
    location: 'Toronto, Canada',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/cohere-product-1',
    source: 'Lever',
    description: 'Build AI-powered products and features using Cohere\'s NLP APIs. Full-stack background with ML experience preferred.',
    posted_at: hoursAgo(14),
  },
  {
    title: 'Deep Learning Infrastructure Engineer',
    company: 'Mistral AI',
    location: 'Paris, France',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/mistral-infra-1',
    source: 'Company Site',
    description: 'Scale training infrastructure for frontier language models. Experience with CUDA, PyTorch distributed, and large-scale cluster management required.',
    posted_at: daysAgo(1),
  },
  {
    title: 'NLP Engineer',
    company: 'Hugging Face',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/hf-nlp-1',
    source: 'Greenhouse',
    description: 'Contribute to the open-source ML ecosystem. Build datasets, models, and evaluation frameworks for the NLP community.',
    posted_at: daysAgo(1),
  },
  {
    title: 'ML Platform Engineer',
    company: 'Scale AI',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/scale-platform-1',
    source: 'Lever',
    description: 'Build internal tooling and MLOps infrastructure to accelerate Scale\'s data annotation and model evaluation workflows.',
    posted_at: daysAgo(2),
  },
  {
    title: 'Generative AI Research Scientist',
    company: 'DeepMind',
    location: 'London, UK',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/deepmind-research-1',
    source: 'Company Site',
    description: 'Conduct research on generative models, multi-modal learning, and AI safety. PhD in machine learning or related field required.',
    posted_at: daysAgo(2),
  },
  {
    title: 'AI Safety Engineer',
    company: 'Anthropic',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/anthropic-safety-1',
    source: 'Greenhouse',
    description: 'Work on interpretability, RLHF, and Constitutional AI techniques. Help ensure AI systems are safe and aligned with human values.',
    posted_at: daysAgo(3),
  },
  {
    title: 'Machine Learning Engineer — Recommendations',
    company: 'Replit',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/replit-ml-1',
    source: 'Lever',
    description: 'Build ML models to personalize the Replit experience for millions of developers. Experience with recommendation systems and online learning.',
    posted_at: daysAgo(3),
  },
  {
    title: 'Senior AI Engineer',
    company: 'Perplexity AI',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/perplexity-ai-1',
    source: 'Company Site',
    description: 'Build AI-powered search and question-answering systems. Strong background in retrieval-augmented generation and search relevance.',
    posted_at: daysAgo(4),
  },
  {
    title: 'LLM Fine-tuning Engineer',
    company: 'Together AI',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/together-finetuning-1',
    source: 'Greenhouse',
    description: 'Own the end-to-end fine-tuning pipeline for customer LLMs. Experience with PEFT, LoRA, and instruction-tuning required.',
    posted_at: daysAgo(4),
  },
  {
    title: 'AI Infrastructure Engineer',
    company: 'Replicate',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/replicate-infra-1',
    source: 'Company Site',
    description: 'Build and scale the infrastructure that runs hundreds of open-source AI models in production. Kubernetes, GPU provisioning, and distributed systems.',
    posted_at: daysAgo(5),
  },
  {
    title: 'Machine Learning Scientist',
    company: 'Waymo',
    location: 'Mountain View, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/waymo-ml-1',
    source: 'Lever',
    description: 'Research and develop ML models for autonomous vehicle perception and prediction. Experience with 3D object detection and temporal modeling.',
    posted_at: daysAgo(5),
  },
  {
    title: 'AI Research Engineer — Multimodal',
    company: 'Runway',
    location: 'New York, NY',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/runway-multimodal-1',
    source: 'Company Site',
    description: 'Push the frontier of video and image generation models. Work closely with researchers to bring new generative AI capabilities to production.',
    posted_at: daysAgo(6),
  },
  {
    title: 'Senior ML Engineer — Search',
    company: 'Elastic',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/elastic-ml-1',
    source: 'Greenhouse',
    description: 'Build ML-powered search relevance and semantic search features. Experience with vector search, embeddings, and search quality evaluation.',
    posted_at: daysAgo(6),
  },
  {
    title: 'MLOps Engineer',
    company: 'Weights & Biases',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/wandb-mlops-1',
    source: 'Lever',
    description: 'Build tooling for ML experiment tracking and model monitoring. Help ML teams move faster with better observability into their training runs.',
    posted_at: daysAgo(7),
  },
  {
    title: 'AI Engineer — Developer Tools',
    company: 'Cursor',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/cursor-ai-1',
    source: 'Company Site',
    description: 'Build the AI-powered code editor used by tens of thousands of engineers. Focus on context retrieval, code generation quality, and model serving.',
    posted_at: daysAgo(7),
  },
  {
    title: 'Machine Learning Engineer — Language',
    company: 'Grammarly',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/grammarly-ml-1',
    source: 'Greenhouse',
    description: 'Improve Grammarly\'s writing suggestions using the latest NLP and LLM techniques. Work on grammar correction, style, and generative writing features.',
    posted_at: daysAgo(8),
  },
  {
    title: 'Research Engineer — RL',
    company: 'xAI',
    location: 'Palo Alto, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/xai-rl-1',
    source: 'Company Site',
    description: 'Work on reinforcement learning from human feedback (RLHF) and reasoning model training. Strong background in RL and large-scale ML systems.',
    posted_at: daysAgo(9),
  },
  {
    title: 'NLP Research Scientist',
    company: 'Bloomberg',
    location: 'New York, NY',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/bloomberg-nlp-1',
    source: 'Lever',
    description: 'Apply NLP to financial data: earnings calls, news, regulatory filings. Build domain-specific language models for the Bloomberg terminal.',
    posted_at: daysAgo(9),
  },
  {
    title: 'ML Engineer — Computer Vision',
    company: 'Samsara',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/samsara-cv-1',
    source: 'Greenhouse',
    description: 'Build computer vision models for fleet safety and operations. Real-time video analytics, object detection, and driver behavior prediction.',
    posted_at: daysAgo(10),
  },
  {
    title: 'AI Researcher — Reasoning',
    company: 'DeepSeek',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/deepseek-reasoning-1',
    source: 'Company Site',
    description: 'Research and improve reasoning capabilities of large language models. Focus on chain-of-thought, tool use, and mathematical reasoning.',
    posted_at: daysAgo(11),
  },
  {
    title: 'LLM Deployment Engineer',
    company: 'Anyscale',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/anyscale-deploy-1',
    source: 'Lever',
    description: 'Build high-performance LLM serving infrastructure on Ray. Experience with vLLM, TensorRT, quantization, and serving at scale.',
    posted_at: daysAgo(12),
  },
  {
    title: 'Machine Learning Engineer — Ads',
    company: 'Reddit',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/reddit-ml-ads-1',
    source: 'Greenhouse',
    description: 'Build ML models for ad targeting, ranking, and optimization. Experience with CTR prediction, embedding models, and real-time inference.',
    posted_at: daysAgo(12),
  },
  {
    title: 'AI Platform Engineer',
    company: 'Notion',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/notion-ai-1',
    source: 'Lever',
    description: 'Build the AI features used by millions of Notion users. LLM integration, prompt engineering, retrieval systems, and latency optimization.',
    posted_at: daysAgo(13),
  },
  {
    title: 'Deep Learning Engineer — Audio',
    company: 'ElevenLabs',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/elevenlabs-audio-1',
    source: 'Company Site',
    description: 'Build neural TTS and voice cloning models. Experience with speech synthesis, audio transformers, and real-time audio generation.',
    posted_at: daysAgo(14),
  },
  {
    title: 'ML Research Engineer — Embeddings',
    company: 'Pinecone',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/pinecone-embeddings-1',
    source: 'Greenhouse',
    description: 'Research and build state-of-the-art embedding models for semantic search. Experience with contrastive learning, bi-encoders, and ANN indices.',
    posted_at: daysAgo(14),
  },
  {
    title: 'AI Engineer — Healthcare',
    company: 'Hippocratic AI',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/hippocratic-ai-1',
    source: 'Lever',
    description: 'Build safe AI agents for healthcare communication. LLM fine-tuning, clinical NLP, and safety evaluation in a highly regulated environment.',
    posted_at: daysAgo(15),
  },
  {
    title: 'Machine Learning Engineer — Robotics',
    company: 'Physical Intelligence',
    location: 'San Francisco, CA',
    is_remote: false,
    url: 'https://mock.liveaijobs.com/jobs/pi-robotics-ml-1',
    source: 'Company Site',
    description: 'Train neural networks that control physical robots. Imitation learning, diffusion policies, and sim-to-real transfer. Cutting-edge research environment.',
    posted_at: daysAgo(15),
  },
  {
    title: 'Senior AI Engineer — Agents',
    company: 'LangChain',
    location: 'Remote',
    is_remote: true,
    url: 'https://mock.liveaijobs.com/jobs/langchain-agents-1',
    source: 'Greenhouse',
    description: 'Build production-grade AI agent frameworks and tooling. Help thousands of developers deploy reliable LLM applications in production.',
    posted_at: daysAgo(16),
  },
]
